# Generated by Django 5.0.3 on 2024-05-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
