# Generated by Django 5.0.3 on 2024-06-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_profile_location_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                default="images/blank_image.jpg", upload_to="media"
            ),
        ),
    ]
