# Generated by Django 5.0.3 on 2024-06-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='images/blank_image.png', upload_to='media'),
        ),
    ]
